#!/bin/sh

mpd_artist=$(mpc -p 6601 -f "%artist%" | head -1)
mpd_title=$(mpc -p 6601 -f "%title%" | head -1)
mpd_album=$(mpc -p 6601 -f "%album%" | head -1)

MPD_MUSIC_PATH="~/Music"
TMP_COVER_PATH="/tmp/mpd-track-cover.jpg"
exiftool -b -Picture "$MPD_MUSIC_PATH/$(mpc -p 6601 --format "%file%" current)" > "$TMP_COVER_PATH"

image="/tmp/mpd-track-cover.jpg"

#execute
notify-send -i "$image" "Artist : $mpd_artist
Song   : $mpd_title
Album  : $mpd_album"