#!/bin/bash
# vim: set fileencoding=utf-8 ts=4 sts=4 sw=4 tw=80 expandtab :
pkill trayer

trayer --edge bottom --align right --widthtype request --heighttype pixel \
       --height 28 --expand true --tint 0x2f343f --transparent true \
       --alpha 0 --margin 420
