#!/bin/bash
pkill n30f
	MUSIC_DIR=~/Music/
	COVER=/tmp/cover.png
	bg=/tmp/begron.png
    back="~/pop-up/cover.png"
    
{	album="$(mpc -p 6601 --format %album% current)"
    file="$(mpc -p 6601 --format %file% current)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"
    covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER" 
    convert "$src" -resize 130 "$COVER"
	convert "$back" -resize 160 "$bg"
    n30f -x 165 -y 24 -d ${bg}
    n30f -x 180 -y 39 -d ${COVER}
} &
